#! /bin/bash
wget -N -t 0 -c www.theweekinchess.com/zips/twic920c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic921c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic922c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic923c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic924c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic925c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic926c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic927c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic928c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic929c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic930c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic931c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic932c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic933c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic934c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic935c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic936c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic937c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic938c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic939c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic940c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic941c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic942c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic943c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic944c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic945c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic946c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic947c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic948c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic949c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic950c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic951c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic952c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic953c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic954c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic955c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic956c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic957c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic958c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic959c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic960c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic961c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic962c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic963c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic964c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic965c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic966c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic967c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic968c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic969c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic970c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic971c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic972c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic973c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic974c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic975c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic976c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic977c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic978c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic979c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic980c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic981c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic982c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic983c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic984c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic985c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic986c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic987c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic988c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic989c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic990c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic991c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic992c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic993c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic994c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic995c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic996c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic997c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic998c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic999c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1000c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1001c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1002c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1003c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1004c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1005c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1006c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1007c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1008c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1009c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1010c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1011c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1012c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1013c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1014c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1015c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1016c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1017c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1018c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1019c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1020c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1021c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1022c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1023c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1024c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1025c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1026c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1027c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1028c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1029c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1030c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1031c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1032c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1033c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1034c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1035c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1036c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1037c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1038c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1039c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1040c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1041c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1042c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1043c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1044c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1045c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1046c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1047c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1048c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1049c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1050c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1051c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1052c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1053c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1054c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1055c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1056c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1057c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1058c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1059c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1060c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1061c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1062c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1063c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1064c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1065c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1066c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1067c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1068c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1069c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1070c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1071c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1072c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1073c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1074c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1075c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1076c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1077c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1078c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1079c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1080c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1081c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1082c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1083c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1084c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1085c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1086c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1087c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1088c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1089c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1090c6.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1091c6.zip
