#! /bin/bash
wget -N -t 0 -c www.theweekinchess.com/zips/twic920g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic921g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic922g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic923g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic924g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic925g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic926g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic927g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic928g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic929g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic930g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic931g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic932g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic933g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic934g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic935g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic936g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic937g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic938g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic939g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic940g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic941g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic942g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic943g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic944g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic945g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic946g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic947g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic948g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic949g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic950g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic951g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic952g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic953g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic954g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic955g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic956g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic957g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic958g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic959g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic960g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic961g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic962g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic963g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic964g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic965g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic966g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic967g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic968g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic969g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic970g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic971g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic972g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic973g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic974g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic975g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic976g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic977g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic978g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic979g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic980g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic981g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic982g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic983g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic984g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic985g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic986g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic987g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic988g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic989g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic990g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic991g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic992g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic993g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic994g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic995g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic996g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic997g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic998g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic999g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1000g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1001g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1002g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1003g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1004g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1005g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1006g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1007g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1008g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1009g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1010g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1011g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1012g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1013g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1014g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1015g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1016g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1017g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1018g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1019g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1020g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1021g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1022g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1023g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1024g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1025g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1026g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1027g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1028g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1029g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1030g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1031g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1032g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1033g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1034g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1035g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1036g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1037g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1038g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1039g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1040g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1041g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1042g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1043g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1044g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1045g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1046g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1047g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1048g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1049g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1050g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1051g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1052g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1053g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1054g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1055g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1056g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1057g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1058g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1059g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1060g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1061g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1062g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1063g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1064g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1065g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1066g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1067g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1068g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1069g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1070g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1071g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1072g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1073g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1074g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1075g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1076g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1077g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1078g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1079g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1080g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1081g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1082g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1083g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1084g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1085g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1086g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1087g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1088g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1089g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1090g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1091g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1092g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1093g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1094g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1095g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1096g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1097g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1098g.zip
wget -N -t 0 -c www.theweekinchess.com/zips/twic1099g.zip
