su -c 'dnf -y groups install c-development'
su -c 'dnf -y groups install development-libs'
su -c 'dnf -y groups install development-tools'
su -c 'dnf -y groups install fedora-packager'
su -c 'dnf -y groups install rpm-development-tools'
su -c 'dnf -y install automake gcc gcc-c++ kernel-devel cmake'
su -c 'dnf -y install python-devel python3-devel'
su -c 'dnf -y install monodevelop'
su -c 'dnf -y install golang'
su -c 'dnf -y install nodejs'
su -c 'dnf -y install rust'
su -c 'dnf -y install cargo'
su -c 'dnf -y install python2-pip'
su -c 'dnf -y install python3-pip'
su -c 'dnf -y install python2-virtualenv'
su -c 'dnf -y install python3-virtualenv'
su -c 'dnf -y install python2-virtualenvwrapper.noarch'
su -c 'dnf -y install python3-virtualenvwrapper.noarch'
